var allCharacters = [
    "Traveler",
    "Alhaitham",
    "Aloy",
    "Amber",
    "Arataki Itto",
    "Baizhu",
    "Barbara",
    "Beidou",
    "Bennett",
    "Candace",
    "Charlotte",
    "Chongyun",
    "Collei",
    "Cyno",
    "Dehya",
    "Diluc",
    "Diona",
    "Dori",
    "Eula",
    "Faruzan",
    "Fischl",
    "Freminet",
    "Furina",
    "Ganyu",
    "Gorou",
    "Hu Tao",
    "Jean",
    "Kaedehara Kazuha",
    "Kaeya",
    "Kamisato Ayaka",
    "Kamisato Ayato",
    "Kaveh",
    "Keqing",
    "Kirara",
    "Klee",
    "Kujou Sara",
    "Kuki Shinobu",
    "Layla",
    "Lisa",
    "Lynette",
    "Lyney",
    "Mika",
    "Mona",
    "Nahida",
    "Navia",
    "Neuvillette",
    "Nilou",
    "Ningguang",
    "Noelle",
    "Qiqi",
    "Raiden Shogun",
    "Razor",
    "Rosaria",
    "Sangonomiya Kokomi",
    "Sayu",
    "Shenhe",
    "Shikanoin Heizou",
    "Sucrose",
    "Tartaglia",
    "Thoma",
    "Tighnari",
    "Traveler",
    "Venti",
    "Wanderer",
    "Wriothesley",
    "Xiangling",
    "Xiao",
    "Xingqiu",
    "Xinyan",
    "Yae Miko",
    "Yanfei",
    "Yaoyao",
    "Yelan",
    "Yoimiya",
    "Yun Jin",
    "Zhongli"
];

var constellationsByCharacter = {
    "Traveler (Anemo)": "Viator_Anemo_Shape",
    "Traveler (Geo)": "Viator_Geo_Shape",
    "Traveler (Electro)": "Viator_Electro_Shape",
    "Traveler (Dendro)": "Viator_Dendro_Shape",
    "Traveler (Hydro)": "Viator_Hydro_Shape",
    "Albedo": "Princeps Cretaceus",
    "Alhaitham": "Vultur Volans",
    "Aloy": "Nora Fortis",
    "Amber": "Lepus",
    "Arataki Itto": "Taurus Iracundus",
    "Baizhu": "Lagenaria",
    "Barbara": "Crater",
    "Beidou": "Victor Mare",
    "Bennett": "Rota Calamitas",
    "Candace": "Sagitta Scutum",
    "Charlotte": "Hualina Veritas",
    "Chevreuse": "Sclopetum Ensiferum",
    "Chongyun": "Nubis Caesor",
    "Collei": "Leptailurus Cervarius",
    "Cyno": "Lupus Aureus",
    "Dehya": "Mantichora",
    "Diluc": "Noctua",
    "Diona": "Feles",
    "Dori": "Magicae Lucerna",
    "Eula": "Aphros Delos",
    "Faruzan": "Flosculi Implexi",
    "Fischl": "Corvus",
    "Freminet": "Automaton",
    "Furina": "Animula Choragi",
    "Gaming": "Leo Expergiscens",
    "Ganyu": "Sinae Unicornis",
    "Gorou": "Canis Bellatoris",
    "Hu Tao": "Papilio Charontis",
    "Jean": "Leo Minor",
    "Kaedehara Kazuha": "Acer Palmatum",
    "Kaeya": "Pavo Ocellus",
    "Kamisato Ayaka": "Grus Nivis",
    "Kamisato Ayato": "Cypressus Custos",
    "Kaveh": "Paradisaea",
    "Keqing": "Trulla Cementarii",
    "Kirara": "Arcella",
    "Klee": "Trifolium",
    "Kujou Sara": "Flabellum",
    "Kuki Shinobu": "Tribulatio Demptio",
    "Layla": "Luscinia",
    "Lisa": "Tempus Fugit",
    "Lumine": "Viatrix",
    "Lynette": "Felis Alba",
    "Lyney": "Felis Fuscus",
    "Mika": "Palumbus",
    "Mona": "Astrolabos",
    "Nahida": "Sapientia Oromasdis",
    "Navia": "Rosa Multiflora",
    "Neuvillette": "Leviathan Judicator",
    "Nilou": "Lotos Somno",
    "Ningguang": "Opus Aequilibrium",
    "Noelle": "Parma Cordis",
    "Qiqi": "Pristina Nola",
    "Raiden Shogun": "Imperatrix Umbrosa",
    "Razor": "Lupus Minor",
    "Rosaria": "Spinea Corona",
    "Sangonomiya Kokomi": "Dracaena Somnolenta",
    "Sayu": "Nyctereutes Minor",
    "Shenhe": "Crista Doloris",
    "Shikanoin Heizou": "Cervus Minor",
    "Sucrose": "Ampulla",
    "Tartaglia": "Monoceros Caeli",
    "Thoma": "Rubeum Scutum",
    "Tighnari": "Vulpes Zerda",
    "Venti": "Carmen Dei",
    "Wanderer": "Peregrinus",
    "Wriothesley": "Cerberus",
    "Xiangling": "Trulla",
    "Xianyun": "Grus Serena",
    "Xiao": "Alatus Nemeseos",
    "Xingqiu": "Fabulae Textile",
    "Xinyan": "Fila Ignium",
    "Yae Miko": "Divina Vulpes",
    "Yanfei": "Bestia Iustitia",
    "Yaoyao": "Osmanthus",
    "Yelan": "Umbrabilis Orchis",
    "Yoimiya": "Carassius Auratus",
    "Yun Jin": "Opera Grandis",
    "Zhongli": "Lapis Dei"
};